---
all:
  children:
    root_ca:
      hosts:
        nomma-rootca01:
          ansible_host: 192.168.122.58
          ansible_user: ldecareaux
          ansible_ssh_private_key_file: ~/.ssh/id_rsa_work
          ansible_python_interpreter: /usr/bin/python3
